version: "3"

services:
  app:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./app/credential/gcp-sa-key.json
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0"]
