name: Test terraform for brain
on:
  push:
    paths:
      - "brain-infra/**"
      - ".github/workflows/brain-infra-test.yaml"

jobs:
  terraform-plan:
    runs-on: ubuntu-20.04
    env:
      DEPLOY_ENV: dev
    defaults:
      run:
        working-directory: ./brain-infra/
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: tflint
        uses: devops-infra/action-tflint@0.1

      - name: GCP setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: wyly-brain-dev
          service_account_key: ${{ secrets.GCP_SA_KEY_DEPLOY_BRAIN_DEV }}
          export_default_credentials: true

      - name: set terraform env
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3
          cli_config_credentials_token: ${{ secrets.GCP_SA_KEY_DEPLOY_BRAIN_DEV }}

      - name: init
        run: terraform init -backend-config "bucket=wyly-brain-tfstate-${DEPLOY_ENV}"
        continue-on-error: false

      - name: create workspace
        run: terraform workspace new ${DEPLOY_ENV}
        continue-on-error: false

      - name: validate
        run: terraform validate
        continue-on-error: true

      - name: plan
        run: terraform plan
