name: Test brain

on:
  push:
    paths:
      - "brain/**"
      - ".github/workflows/brain-test.yaml"

defaults:
  run:
    working-directory: brain

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup env
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run pytest
        run: |
          pipenv run pytest
      - name: Run flake8
        run: |
          pipenv run flake8 ./app
