name: Test & Lint brain

on:
  push:
    paths:
      - "brain/**"
      - ".github/workflows/brain-test.yaml"

defaults:
  run:
    working-directory: brain

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.6"
      - name: install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: setup virtual env
        run: poetry install
      - name: unit test
        run: poetry run pytest .
      - name: static code analysis
        run: |
          poetry run black . --check
          poetry run isort . --check
          poetry run mypy .
          poetry run flake8 .
