name: Deploy infra of brain on dev
on:
  push:
    branches:
      - develop
    paths:
      - "brain-infra/**"
      - ".github/workflows/brain-infra-deploy-dev.yaml"

jobs:
  terraform-plan:
    runs-on: ubuntu-20.04
    env:
      DEPLOY_ENV: dev
    defaults:
      run:
        working-directory: ./brain-infra/
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: GCP setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: wyly-brain-dev
          service_account_key: ${{ secrets.GCP_SA_KEY_DEPLOY_BRAIN_DEV }}
          export_default_credentials: true

      - name: set terraform env
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3
          cli_config_credentials_token: ${{ secrets.GCP_SA_KEY_DEPLOY_BRAIN_DEV }}

      - name: init
        run: terraform init -backend-config "bucket=wyly-brain-tfstate-${DEPLOY_ENV}"
        continue-on-error: false

      - name: select workspace
        run: terraform workspace select ${DEPLOY_ENV}
        continue-on-error: false

      - name: apply
        run: terraform apply -auto-approve

      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Deploy infra to Dev Brain"
          mention: "here"
          mention_if: "failure"
          channel: "#wyly-github"
          icon_emoji: "terraform"
          username: "terraform"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
